using System.Text;

namespace Server.Misc
{
    class ChangeLog
    {
		public static string Version()
		{
			return "Version: 1.3.0";
		}

		public static string Versions()
        {
			const string SEPARATOR_LINE = "<br>---------------------------------------------------------------------------------<br><br>";
			var builder = new StringBuilder();
			builder.Append(Version() + "<br>");

			builder.Append("Changes<br>");
			builder.Append("- Champs - Rikktor is now much harder<br>");
			builder.Append("- Champs - Barracoon's mobs can no longer rummage<br>");
			builder.Append("- Champs - All minions should now be aggressive<br>");
			builder.Append("- Gather - Reduce logs per tree from 4-9 to 4-6<br>");
			builder.Append("- Gather - Lumberjacking sparkles now have a light source<br>");
			builder.Append("- Gump - Completely redesigned Runebook gump<br>");
			builder.Append("- Item - Acidic robe cooldown reduced to 10 minutes (will be reworked in a future update)<br>");
			builder.Append("- Item - High fame mobs can now drop Champion Skulls<br>");
			builder.Append("- Item - Lawn tools can now be used indoors<br>");
			builder.Append("- Item - Mushrooms are now stackable<br>");
			builder.Append("- Item - Added new item to help with goldsplosions<br>");
			builder.Append("- Item - Update champion skull decay strategy and labels<br>");
			builder.Append("- Misc - Champion spawns are now added to the world<br>");
			builder.Append("- Misc - Jewelry trap has been reworked to be less aggressive<br>");
			builder.Append("- Misc - Quest pedestal generation is now more resilient<br>");
			builder.Append("- Misc - Horde Minions now loot items much faster<br>");
			builder.Append("- Mobs - Players are now immune to peacemaking for 30s after it ends<br>");
			builder.Append("- NPC - Mercantile/guild barter bonus is reduced to +100% of item value, down from +300%<br>");
			builder.Append("- NPC - Mercantile/guild bonus now increases the amount of Gold that vendors have available for purchase<br>");
			builder.Append("- Settings - Gold cut rate increased to 35%, up from 25%<br>");
			builder.Append("- Spell - AOE damage spells are now reduced to a minimum of 50% damage when hitting more than one target<br>");

			builder.Append("<br>");
			builder.Append("Fixes<br>");
			builder.Append("- Spell - Wrath no longer does doubles damage to one target<br>");
			builder.Append("- Misc - More Fast-player changes<br>");
			builder.Append("- Misc - Remove bad images from manage Player Vendor gump<br>");
			builder.Append("- Misc - Traps are now being checked for players with >= 5.0 Remove Trap<br>");
			builder.Append("- Misc - Fix crash when a sailor died without a player killer<br>");
			builder.Append("- Misc - Fix crash when a magic carpet is drydocked when someone else is in the Lower Deck zone<br>");
			builder.Append("- Misc - Familiars now drop their backpack contents on server restart<br>");
			builder.Append("- Item - Quick fix to prevent crash with locked containers<br>");
			builder.Append("- Item - Orphaned projectiles are no longer created when using a ranged weapon<br>");
			builder.Append("- Item - Orphaned clothing are no longer created during dress up<br>");
			builder.Append(SEPARATOR_LINE);

			///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

			builder.Append("Version: 1.2.0<br>");

			builder.Append("Changes<br>");
			builder.Append("- Admin - Add '[Freeze-SetId' command to set the Freezable Item ID<br>");
			builder.Append("- Combat - Updated OmniAI ranged preference logic<br>");
			builder.Append("- Craft - Lapidary tools now apply magical attributes to crafted items<br>");
			builder.Append("- Craft - Stitching tools now apply magical attributes to crafted items<br>");
			builder.Append("- Craft - Royal loin cloth are now craftable<br>");
			builder.Append("- Craft - Skill requirements are now indicated on the Resource selection page<br>");
			builder.Append("- Gump - Add tooltips to the crafting gump<br>");
			builder.Append("- Item - Potion of Rebirth is now converted to a soul orb upon use<br>");
			builder.Append("- Item - Soul Orb now has a confirmation prompt<br>");
			builder.Append("- Item - Soul Orb timer repeats and restarts when logging in<br>");
			builder.Append("- Item - Lawn tools and Remodeling tools now have a Remove Target button on the Remove All page<br>");
			builder.Append("- Item - Lawn tools and Remodeling tools no longer remove when double-clicked<br>");
			builder.Append("- Item - Jars of wax are now more effective on instruments<br>");
			builder.Append("- Item - Legendary Artefacts (LA) rework<br>");
			builder.Append("       - Max level is now 40<br>");
			builder.Append("       - Points are 5 per level, resulting in a maximum of 200 points<br>");
			builder.Append("       - Experience from each LA has been extracted into a token and the LA has been reset<br>");
			builder.Append("         (Luck and Damage Increase values were left in place)<br>");
			builder.Append("- Misc - ID skills rework<br>");
			builder.Append("       - Unidentified item drop chance is now tied to the level of the skill used to ID it<br>");
			builder.Append("         The highest skill from all damaging players will be used<br>");
			builder.Append("       - Added breakpoints to bypass RNG at 0/30/60 skill<br>");
			builder.Append("         Skill beyond 60 will only matter when more than 3 items drop<br>");
			builder.Append("       - Scenario - 2 items drop<br>");
			builder.Append("         At 20 skill, 1 item will be guaranteed<br>");
			builder.Append("           The other item will have a 20/125 chance to drop<br>");
			builder.Append("         At 30+ skill, both items will be guaranteed<br>");
			builder.Append("       - Scenario - 5 items drop<br>");
			builder.Append("         At 20 skill, 1 item will be guaranteed<br>");
			builder.Append("           The remaining 4 items will have a 20/125 chance to drop<br>");
			builder.Append("         At 30 skill, 2 items will be guaranteed<br>");
			builder.Append("           The remaining 3 items will have a 30/125 chance to drop<br>");
			builder.Append("         At 60 skill, 3 items will be guaranteed<br>");
			builder.Append("           The remaining 2 items will have a 60/125 chance to drop<br>");
			builder.Append("         At 70 skill, 3 items will be guaranteed<br>");
			builder.Append("           The remaining 2 items will have a 70/125 chance to drop<br>");
			builder.Append("- Misc - Vendor purchase price changes<br>");
			builder.Append("       - Skins, Blocks, and non-craftable Alien resources now sell for notably less<br>");
			builder.Append("       - Leather, Ingot, and Board prices have been rebalanced<br>");
			builder.Append("- Misc - Relic decorative items now drop much more frequently<br>");
			builder.Append("- Misc - Reduced amount of items per pack animal to 50, down from 125<br>");
			builder.Append("- Misc - Trap doors have been rebalanced<br>");
			builder.Append("       - Reduced chance of extra container dropping<br>");
			builder.Append("       - Extra container can no longer be double filled<br>");
			builder.Append("- Misc - [c is now sent as a Global Chat message<br>");
			builder.Append("- Misc - Gold is now worth twice as much when gathering Piety and Souls<br>");
			builder.Append("- Misc - Rare drops from non-player kills now only use half of a player's luck<br>");
			builder.Append("- Mobs - Mobs drop less gems<br>");
			builder.Append("- Mobs - Fire salamander special drop is no longer guaranteed<br>");
			builder.Append("- Mobs - Ancient tree special drop is no longer guaranteed<br>");
			builder.Append("- NPC - Vendor gold is generated per-account instead of for the entire world<br>");
			builder.Append("- NPC - Necromancer guildmaster now sells witch reagents<br>");
			builder.Append("- Pets - Pets in the world no longer lose loyalty when the Player is offline<br>");
			builder.Append("- Quest - Update final messaging for Skara<br>");
			builder.Append("- Skill - Discordance skill has been reworked<br>");
			builder.Append("        - No longer usable by Players against Players<br>");
			builder.Append("        - Reduces Resists and Skills (stat reduction was removed)<br>");
			builder.Append("        - Utilizes a rolling duration, so it can be spammed on the same target<br>");
			builder.Append("        - Duration increase is now 10s for success and 4s for failure<br>");
			builder.Append("- Skill - Mercantile can now be gained from npc transactions (Buy/Sell/Shoppes)<br>");
			builder.Append("- Skill - Searching is now limited to 1 bonus skill check per points<br>");

			builder.Append("<br>");
			builder.Append("Fixes<br>");
			builder.Append("- Craft - Stitching tools now work for Miscellaneous category<br>");
			builder.Append("- Misc - Gold drops now vary per loot pack<br>");
			builder.Append("- Misc - Fix an issue with chugging unidentified drinks<br>");
			builder.Append("- Misc - Unidentified drinks no longer get chugged when double-clicked<br>");
			builder.Append("- Misc - Players may now mark/recall from the Ambrosia dungeon home<br>");
			builder.Append("- Misc - Double-click to equip throw/pugilist gloves now properly removes glove armor<br>");
			builder.Append("- Misc - Enemies killed by Provoked mobs now qualify for rare drops<br>");
			builder.Append("- Quest - Fix issue where Taz gridloot wouldn't trigger on quest item you had to double-click<br>");
			builder.Append("- Pets - Fix issue that would prevent treasure hoard spawning and quest completion<br>");
			builder.Append("- Spell - Sanctify now conveys the proper buff duration<br>");
			builder.Append(SEPARATOR_LINE);

			///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

			builder.Append("Version: 1.1.0<br>");

			builder.Append("Changes<br>");
			builder.Append("- Combat - Add teleport cooldown for OmniAI<br>");
			builder.Append("- Combat - Mobs that can only swim can no longer teleport<br>");
			builder.Append("- Combat - Creatures will no longer begin combat with self-buffing<br>");
			builder.Append("- Craft - BlankScroll, Bottle, and Jar are no longer considered Resources (they're cheaper to buy)<br>");
			builder.Append("- Craft - Jars can now be bought from Alchemist and Herbalist<br>");
			builder.Append("- Craft - Druidic Herbalism now takes 4 total reagents, up from 2<br>");
			builder.Append("- Craft - Witch Brewing now takes 4 total reagents, up from 2<br>");
			builder.Append("- Craft - Crafting any scroll can now be used to reach 125 Inscription<br>");
			builder.Append("- Craft - Dwarven ore now yields 2 ingots per ore, down from 4<br>");
			builder.Append("- Gump - Tillerman gump now has tooltips<br>");
			builder.Append("- Item - Retroactive nerfs to Indecency and Gargoyle Shield<br>");
			builder.Append("- Item - Retroactive buffs to Polar bear cape, Polar bear boots, Grim Reaper's Robe, Robe of Teleport<br>");
			builder.Append("- Item - Rebalancing changes to Royal Guard Sash<br>");
			builder.Append("- Item - Nerfs to Shroud of Shadows, Jade Scimitar<br>");
			builder.Append("- Item - Buffs to Earrings of Health, Grim Reaper's lantern, Wildfire bow<br>");
			builder.Append("- Item - Elixirs can now only exceed your skill cap by 5<br>");
			builder.Append("- Misc - BarkFragment, BlankMap, WheatSheaf, and Sand can now be sold<br>");
			builder.Append("- Misc - Add a 'clear the deck' phrase to remove corpses from boat<br>");
			builder.Append("- Misc - Library now has placeholder text<br>");
			builder.Append("- Misc - Thief pedestals now provide more variety by default<br>");
			builder.Append("- NPC - Always announce gold when buy/sell<br>");
			builder.Append("- NPC - Vendor bought equipment is now limited to 1g resale value<br>");
			builder.Append("- NPC - Max properties from vendor-bought magical items is now 4, down from 5<br>");
			builder.Append("- Pets - Tooltip now shows 'real' level, which matters when pets de-level<br>");
			builder.Append("- Quest - Display rumor count after last Sage Artifact rumor is verified<br>");
			builder.Append("- Shoppe - Targeting a container now adds all possible items to the Order<br>");
			builder.Append("- Shoppe - All Shoppes (except Cartography) now have Orders<br>");
			builder.Append("- Shoppe - Baker shoppe Orders can no longer require wasabi clumps<br>");
			builder.Append("- Shoppe - Use correct tool names<br>");

			builder.Append("<br>");
			builder.Append("Fixes<br>");
			builder.Append("- Combat - Feint weapon ability now properly reduces damage<br>");
			builder.Append("- Gather - Lumberjacking in the dreaded place has increased yields<br>");
			builder.Append("- Map - Add teleporters to bridge in Savaged Empire<br>");
			builder.Append("- Misc - Sacrificing the Dark Core of Exodus now only deletes your own core<br>");
			builder.Append("- Misc - Fix an issue with Fast-move delay causing monster ghost speed to be slowed down<br>");
			builder.Append("- Misc - Thief artifact decorations could be purchased for 0g from Sage<br>");
			builder.Append("- Misc - The Merchant Advertiser now works for Sosaria and Underworld<br>");
			builder.Append("- Pets - Fix issue where applying Traits could lower stats<br>");
			builder.Append("- Misc - Weapon Abilities now respect ServerSettings cap for Lower Mana Cost (no change for Live)<br>");
			builder.Append("- Misc - Autoloot no longer works on Player corpses<br>");
			builder.Append("- Misc - Autoloot no longer works on corpses where looting would be a criminal action<br>");
			builder.Append("- Misc - Fix message when carving wood corpses<br>");
			builder.Append("- Quest - Sage Artifact now references Land instead of Map<br>");
			builder.Append("- Quest - Fix hiking boots typo in beginner hints<br>");
			builder.Append("- Quest - Fix an issue where only a small subset of Citizens could satisfy the Sage Artifact rumor objective<br>");
			builder.Append("- Race - Logging in as dead non-humans now leaves your body id alone<br>");
			builder.Append(SEPARATOR_LINE);

			///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

			builder.Append("Version: 1.0.2<br>");

			builder.Append("Breaking Changes<br>");
			builder.Append("- Commands - [Cacheclear command has been added<br>");
			builder.Append("- Race - (did not actually work) Logging in as dead non-humans now leaves your body id alone<br>");

			builder.Append("Changes<br>");
			builder.Append("- Augment - Resources no longer give weapons resists<br>");
			builder.Append("- Augment - Gilding benefits have been reduced<br>");
			builder.Append("- Augment - Elemental forging has been improved<br>");
			builder.Append("- Commands - Added experimental [SuppressTooltips for MobileUO<br>");
			builder.Append("- Craft - Add Shuriken to recipe list<br>");
			builder.Append("- Craft - Add Orders to Shoppes<br>");
			builder.Append("- Craft - Non-basic resource skill requirements have increased<br>");
			builder.Append("- Craft - Add Tinker recipes for different skill types<br>");
			builder.Append("- Enchant - Resist attribute cost is now 5, up from 2<br>");
			builder.Append("- Gather - Double-clicking glistening veins indicate when out of range<br>");
			builder.Append("- Gather - Ingot values have been reduced by 25%<br>");
			builder.Append("- Item - Legendary Artifact (not weps) now come with 2 resist all<br>");
			builder.Append("- Item - Legendary Artifact max level is now 50, down from 100<br>");
			builder.Append("- Item - Remove more Dwarven/Elven/Cadalyte item drops<br>");
			builder.Append("- Item - Reduce points on most relic rewards<br>");
			builder.Append("- Item - Merchant Crates have been replaced by Dungeoneer Crates<br>");
			builder.Append("- Item - Runebooks no longer have a cooldown<br>");
			builder.Append("- Item - Soul Orb now persists between server restarts<br>");
			builder.Append("- Item - Soul Orb can be deleted when used<br>");
			builder.Append("- Misc - Containers now have a default max weight of 550, up from 400<br>");
			builder.Append("- Misc - Death robes no longer automatically stack up in your backpack<br>");
			builder.Append("- Misc - Reduced gem block resources from carving<br>");
			builder.Append("- Misc - Merchant crates have been disabled<br>");
			builder.Append("- Misc - Being jailed no longer deletes jewelry<br>");
			builder.Append("- Misc - Being jailed only deletes money<br>");
			builder.Append("- Misc - Spare Copper/Silver no longer drop into your backpack during coin conversion<br>");
			builder.Append("- Misc - SOSes no longer have a chance for a 2nd artifact<br>");
			builder.Append("- Misc - Dramatically reduced Scroll of Transcendence values from treasure maps<br>");
			builder.Append("- Misc - Treasure Maps now have a chance to drop multiple Scroll of Transcendence<br>");
			builder.Append("- Mobs - Mobs are now less likely to curse<br>");
			builder.Append("- Mobs - Increased chance of mana drain when Players have Elementalism<br>");
			builder.Append("- Mobs - Casters can now move with a spell target up<br>");
			builder.Append("- Mobs - Casters can now teleport<br>");
			builder.Append("- NPC - Increased gold cap for vendors in most lands<br>");
			builder.Append("- Pets - Docile pets who are bonded now lose less loyalty per tick<br>");
			builder.Append("- Pets - Pets with low loyalty warn sooner<br>");
			builder.Append("- Pets - Hitpoints/Mana traits now cap at +50%, up from +25%<br>");
			builder.Append("- Quest - Add Recruiters to additional locations<br>");
			builder.Append("- Quest - Clarified Sage artifact quest objectives<br>");
			builder.Append("- Quest - Added pity system for Sage artifact quest objectives<br>");
			builder.Append("- Skill - Magic Resist is now 4x more likely to gain<br>");
			builder.Append("- Skill - Remove Trap is now 4x more likely to gain<br>");
			builder.Append("- Skill - Searching is now 4x more likely to gain<br>");
			builder.Append("- Skill - Stealthing is now 2x more likely to gain<br>");
			builder.Append("- Skill - Discord failure cooldown is 3s, down from 12s<br>");
			builder.Append("- Skill - Pseudo-grandmaster Seafarers no longer need docks for boats<br>");
			builder.Append("- Spell - Curse now reduces max Resistance for Players by 10<br>");
			builder.Append("- Spell - You may now fast travel out of the lost land<br>");

			builder.Append("<br>");
			builder.Append("Fixes<br>");
			builder.Append("- Gump - Craft Skill List now confirms you have all skills<br>");
			builder.Append("- Gump - Crafting Session now accurately reports Exceptional<br>");
			builder.Append("- Gump - Fix null ref when TextEntry was null<br>");
			builder.Append("- Gump - Fix overlapping properties on clothing enhancement<br>");
			builder.Append("- Item - Auto-skinning no longer performs criminal acts<br>");
			builder.Append("- Item - Legendary Artifact trinkets didn't repair<br>");
			builder.Append("- Item - Staff of Five parts would not spawn for Mages<br>");
			builder.Append("- Item - Armor/Clothing now show durability at all times<br>");
			builder.Append("- Item - Fixed an issue where Hiking Boots could never drop<br>");
			builder.Append("- Item - Transmutation Potion is only usable on equippable gear<br>");
			builder.Append("- Misc - Fix empty unidentified items<br>");
			builder.Append("- Misc - Treasure hoards now properly limit item attributes to 6<br>");
			builder.Append("- Misc - Fix an issue with Fast-move spells and items when logging in to a slow area<br>");
			builder.Append("- Misc - Ethereal Daemon Mount now has a body<br>");
			builder.Append("- Misc - Fix incorrect entrance hint to Carthax Lake<br>");
			builder.Append("- Misc - Fix an issue when attempting to re-purchase an item from a Citizen<br>");
			builder.Append("- Mobs - Fix an issue where mobs cast curse too much<br>");
			builder.Append("- Mobs - Fix an issue where mobs unintentionally prioritized mana drain over poison<br>");
			builder.Append("- Mobs - Xormite elementals now drop the proper resource<br>");
			builder.Append("- Mobs - Tritun now have resists<br>");
			builder.Append("- Mobs - Fix stack overflow from Jester pranks<br>");
			builder.Append("- Pets - Fix an issue where mobs didn't stop healing when dead<br>");
			builder.Append("- Pets - Fix an issue where some pack animal types could be stabled with items<br>");
			builder.Append("- Pets - Fix an issue where pets who lost levels could not level up again<br>");
			builder.Append("- Pets - Fix an issue where applying traits used boosted values<br>");
			builder.Append("- Quest - Fix null ref crash after [buildworld and restart<br>");
			builder.Append("- Quest - Prematurely turning in a quest tome now returns it<br>");
			builder.Append("- Shoppe - Now properly rejects Tools when full<br>");
			builder.Append("- Spell - Chain Lightning no longer does doubles damage to one target<br>");
			builder.Append("- Spell - Fix bad message for Reveal spells that fail to cast<br>");
			builder.Append(SEPARATOR_LINE);

			///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

			builder.Append("Version: 1.0.1<br>");

			builder.Append("Changes<br>");
			builder.Append("- Craft - Merchant crates have been reduced to a 4 hour timer<br>");
			builder.Append("- Craft - Merchant crates no longer have a gold limit<br>");
			builder.Append("- Enhance - Self repair can now be added to clothing<br>");
			builder.Append("- Gump - Update spiritualism details<br>");
			builder.Append("- Gather - Cutting basic logs difficult reduced to 20, down from 40<br>");
			builder.Append("- Item - Merchant crates no longer accept raw resources<br>");
			builder.Append("- Item - Notify players that lumberjacking is required to use a sawmill<br>");
			builder.Append("- Item - Resists on shirts + chest armor now stack<br>");
			builder.Append("- Item - Use Best Weapon Skill (UBWS) now checks against Fistfighting<br>");
			builder.Append("- Item - Instruments can now be used from your backpack<br>");
			builder.Append("- Item - Play instruments now has a 1s cd, down from 7s<br>");
			builder.Append("- Mobs - Thieves and Spiders no longer have a chance to delete when hiding<br>");
			builder.Append("- Races - An additional source of food has been added<br>");

			builder.Append("<br>");
			builder.Append("Fixes<br>");
			builder.Append("- Boat - Fix issue where hatch would player block movement<br>");
			builder.Append("- Craft - Merchant crates no longer accept raw resources<br>");
			builder.Append("- Craft - Removing the tool from your hand will stop the session<br>");
			builder.Append("- Craft - Fix incorrect mobs dropping Xeno bones<br>");
			builder.Append("- Craft - All barbecue cooking requires heat again<br>");
			builder.Append("- Item - WizardWand now respects the proper LMC limit<br>");
			builder.Append("- Misc - Lockpicking starter chest is now movable<br>");
			builder.Append("- Misc - Fast-move spells and items now work on Login<br>");
			builder.Append("- Misc - Maybe fixed unreproducible fast ghost issue when changing facets<br>");
			builder.Append("- Misc - Fix issue where the Powerscroll gump was giving the wrong scroll types<br>");
			builder.Append("- Pets - Feeding pets now refreshes Loyalty property<br>");
			builder.Append("- Pets - Adding Hitpoints trait now heals the petbr>");
			builder.Append(SEPARATOR_LINE);

			///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

			builder.Append("Version: 1.0.0<br>");

			builder.Append("Changes<br>");
			builder.Append("- Combat - Mob Peacemaking duration is now a function of mob skill<br>");
			builder.Append("- Combat - Add short cooldown to defensive dispelling<br>");
			builder.Append("- Combat - Most mobs now use OmniAI<br>");
			builder.Append("- Combat - Defensive dispel (when mobs are hit) now costs whichever is greater, 40 mana or 10% of max mana<br>");
			builder.Append("- Commands - Add [VendorGold setting to disallow the Vendor's Sell limit safeguard<br>");
			builder.Append("- Commands - Add [Toolbars command to shortcut to Help->Magic Toolbars<br>");
			builder.Append("- Craft - Bulk crafting has been completely redone<br>");
			builder.Append("- Craft - Using non-basic resources can now yield multiple skill gains<br>");
			builder.Append("- Craft - Items can only be enhanced if they are basic resources<br>");
			builder.Append("- Craft - Add ability to break down all items in a container<br>");
			builder.Append("- Craft - Cut/Break down no longer requires 50 skill<br>");
			builder.Append("- Craft - Bulk crafting no longer resets Stat Gain cooldown<br>");
			builder.Append("- Craft - Merchant crates now have 24 hour timer<br>");
			builder.Append("- Craft - Large BODs can no longer generate the required Small BODs<br>");
			builder.Append("- Craft - Leather Cloaks/Robes are no longer craftable<br>");
			builder.Append("- Craft - Disable Bulk Order Deeds (needs fixing/balancing)<br>");
			builder.Append("- Craft - Reaper oil and Mystical tree sap no longer drop<br>");
			builder.Append("- Craft - Bark fragments now come from Lumberjacking instead of Carpentry<br>");
			builder.Append("- Craft - Exceptionally crafted items are guaranteed a minor magical property<br>");
			builder.Append("- Craft - Exceptionally crafted weapons now have 20% Damage Increase (DI), down from 35%<br>");
			builder.Append("- Craft - Exceptionally crafted weapons now get +1% DI per 10 skill in Arms Lore<br>");
			builder.Append("- Craft - Exceptionally crafted weapons now get +3% DI for 125 skill in Arms Lore (+15% total)<br>");
			builder.Append("- Craft - Exceptionally crafted shields now get resist bonuses<br>");
			builder.Append("- Craft - Exceptionally crafted armor now get 3 bonus resistance points, down from 15<br>");
			builder.Append("- Craft - Exceptionally crafted hats now require Arms Lore for bonus resistance points<br>");
			builder.Append("- Craft - Alien resources (from AoA) are no longer craftable<br>");
			builder.Append("- Craft - Add Skill List to assist with finding items to craft for gains<br>");
			builder.Append("- Craft - Add Blank Map recipe to Cartography<br>");
			builder.Append("- Craft - Cartography can now use Blank Map or Blank Scroll as a material<br>");
			builder.Append("- Craft - Cartography skill requirements have been reworked<br>");
			builder.Append("- Craft - Each Bark Fragment now creates 10x Blank scrolls<br>");
			builder.Append("- Craft - Dwarven/Elven/Alien now require 125 skill<br>");
			builder.Append("- Craft - Non-basic resources no longer give crafting skill bonus<br>");
			builder.Append("- Craft - Shoppes have been redesigned, they are now bound to your Account<br>");
			builder.Append("- Craft - Many Inscription scroll recipes have been temporarily locked<br>");
			builder.Append("- Enchantment - Lower Mana Cost (LMC) is now capped at 8%<br>");
			builder.Append("- Enchantment - Lower Reagent Cost (LRC) is now capped at 20%<br>");
			builder.Append("- Gather - Add 'Rich Trees' to give Lumberjacking a more active playstyle<br>");
			builder.Append("- Gather - Add 'Glistening ore vein' to give Mining a more active playstyle<br>");
			builder.Append("- Gather - Dwarven ore can now only be acquired via 'Glistening ore vein'<br>");
			builder.Append("- Gather - Increased Nepturite spawn rate<br>");
			builder.Append("- Gather - Each Log is now worth 2 Boards<br>");
			builder.Append("- Gather - Logs now weigh 2 stone, up from 0.5<br>");
			builder.Append("- Gather - Logs can now be used while on a pack animal<br>");
			builder.Append("- Gather - Sawing logs now acts as if it was done individually<br>");
			builder.Append("- Gather - Ore now weighs 2 stone, up from 0.5<br>");
			builder.Append("- Gather - Ore now only comes in the large size<br>");
			builder.Append("- Gather - Ore can now be used while on a pack animal<br>");
			builder.Append("- Gather - Smelting ore now acts as if it was done individually<br>");
			builder.Append("- Gather - Ore veins have been reduced and are now 5 to 17, down from 10 to 34<br>");
			builder.Append("- Gather - Crops within 1 tile are automatically harvested<br>");
			builder.Append("- Gather - Tool uses are reduced by the quantity of resources harvested<br>");
			builder.Append("- Gather - One log now yields four boards<br>");
			builder.Append("- Gather - Gains from digging Iron ore stop at 85, down from 100<br>");
			builder.Append("- Gather - Elven wood can now only be acquired via 'Rich Tree'<br>");
			builder.Append("- Gather - Gemstones are now announced when harvested<br>");
			builder.Append("- Gather - Harvest failures now consume Uses Remaining<br>");
			builder.Append("- Gather - Harvest failures now consume node capacity<br>");
			builder.Append("- Gather - Skinning knives have been refactored and are no longer weapons<br>");
			builder.Append("- Gump - Redesigned crafting tool gump<br>");
			builder.Append("- Gump - Redesigned Druidism gump<br>");
			builder.Append("- Gump - Add required skill to Animal Form gump<br>");
			builder.Append("- Gump - Spell toolbar config pages now have close/open buttons<br>");
			builder.Append("- Guilds - Local Guilds bulletin is now sorted by guild<br>");
			builder.Append("- Item - Increased the cost of all 115/120/125 Powerscrolls<br>");
			builder.Append("- Item - Powerscrolls now have to be used in order<br>");
			builder.Append("- Item - Powerscrolls purchases can now use Checks in your Bank<br>");
			builder.Append("- Item - Powerscrolls purchases can now use Gold in your Inventory<br>");
			builder.Append("- Item - The luck bonus for Lucky horse shoe is now 100 per item<br>");
			builder.Append("- Item - Artifacts no longer have enchantment points<br>");
			builder.Append("- Item - Dungeon Chests now allow for multiple Stealing attempts<br>");
			builder.Append("- Item - Oil cloth are now stackable<br>");
			builder.Append("- Item - Quiver Damage Modifier has been reduced to 10%<br>");
			builder.Append("- Item - Books are deleted after memorizing them<br>");
			builder.Append("- Item - Scepter/Stave now have Spell Channeling by default<br>");
			builder.Append("- Item - Bank vaults are now sold by Bankers<br>");
			builder.Append("- Item - Laser swords no longer drop<br>");
			builder.Append("- Item - Runic tools no longer drop<br>");
			builder.Append("- Item - Skill bonuses from items no longer overcap<br>");
			builder.Append("- Item - Hiking Boots no longer give resistances<br>");
			builder.Append("- Item - Soulstones are now account bound upon first use<br>");
			builder.Append("- Item - Magic wands attributes are notably weaker<br>");
			builder.Append("- Item - Magic spellbooks no longer get random spells<br>");
			builder.Append("- Item - Pearl jewelry now has a minimum requirements to drop<br>");
			builder.Append("- Item - Dramatically reduce the sale price of Skins<br>");
			builder.Append("- Item - Ten foot poles have been rebalanced<br>");
			builder.Append("- Item - Equation for damaging items has been changed<br>");
			builder.Append("- Item - Double-clicking a one or two-handed item will equip it<br>");
			builder.Append("- Item - Remove Damage Modifier from Quivers<br>");
			builder.Append("- Item - Redo properties for Artifact Quivers<br>");
			builder.Append("- Item - Boost physical resist of Aegis set<br>");
			builder.Append("- Item - All clothing now have durability<br>");
			builder.Append("- Item - Stop deleting trail maps for undiscovered worlds<br>");
			builder.Append("- Item - Default bandage range has been increased to 3, up from 2<br>");
			builder.Append("- Item - Cotton/Flax/Wool/Thread no longer has to be in your backpack to use<br>");
			builder.Append("- Item - Sharpening stone rework<br>");
			builder.Append("       - Centralized behvaiors for consistency<br>");
			builder.Append("       - Elemental sharpening stones no longer add Damage Increase %<br>");
			builder.Append("       - Consecrated sharpening stones no longer bless and have a duration of 1 hour<br>");
			builder.Append("       - Sharpening stone work on Bladed weapons<br>");
			builder.Append("       - Added sharpening stone variant for Bow weapons<br>");
			builder.Append("       - Added sharpening stone variant for Bludgeoning weapons<br>");
			builder.Append("- Misc - Reduce packhorse max weight to 2400, down from 65000<br>");
			builder.Append("- Misc - Reduce max properties from randomly generated items from 16 to 8<br>");
			builder.Append("- Misc - Fugitives are now considered 'Evil'<br>");
			builder.Append("- Misc - Increased gold values for Coffers<br>");
			builder.Append("- Misc - Dramatically reduced amount of properties from drops<br>");
			builder.Append("- Misc - Dramatically reduced attribute intensity from drops<br>");
			builder.Append("- Misc - Add smooth boat movement<br>");
			builder.Append("- Misc - Add Buff icons to convey stat gain cooldown<br>");
			builder.Append("- Misc - Vendor restock has been reduced to 30 min<br>");
			builder.Append("- Misc - Guildmaster vendor gold has been reduced<br>");
			builder.Append("- Misc - Vendor gold is now '?' by default<br>");
			builder.Append("- Misc - Vendor gold is now regenerated by Player Buy/Sell requests<br>");
			builder.Append("- Misc - Replaced Necromancer character template with Knight<br>");
			builder.Append("- Misc - Replaced Thief character template with Ninja<br>");
			builder.Append("- Misc - Vendors sell magical items based on player Fame and Karma breakpoints<br>");
			builder.Append("- Misc - Identifying items will now stack automatically<br>");
			builder.Append("- Misc - Ghosts now run at mounted speed<br>");
			builder.Append("- Misc - Add [CombatBar to [QuickBar<br>");
			builder.Append("- Misc - Characters now start items relevant to their skills<br>");
			builder.Append("- Misc - Increase 'Vendor Buy' listening distance to 2<br>");
			builder.Append("- Misc - Ninja/Bushido moves may be used while in Animal Form<br>");
			builder.Append("- Misc - Weapon Abilities may be used while in Animal Form<br>");
			builder.Append("- Misc - Add Jako Pet Leveling<br>");
			builder.Append("- Misc - Disable Lighting burnout<br>");
			builder.Append("- Misc - Graverobbing spawns are now a function of Forensics skill level<br>");
			builder.Append("- Misc - Orb of trap finding now caps at 66%<br>");
			builder.Append("- Misc - Changed drops for Treasure Chests<br>");
			builder.Append("- Misc - Add Secondary Skills that do not impact total skill cap<br>");
			builder.Append("       - Alchemy, Blacksmith, Bowcraft, Carpentry, Cooking, Inscription, Tailoring, Tinkering<br>");
			builder.Append("       - Forensics, Lumberjacking, Mining<br>");
			builder.Append("- Pets - Damage to pets is now 140%, down from 200%<br>");
			builder.Append("- Pets - Crit chance to pets is now 5%, down from 20%<br>");
			builder.Append("- Pets - Most Tames get a 25% Stat reduction after Taming<br>");
			builder.Append("- Pets - Tames are reduced to level 1 after being Tamed<br>");
			builder.Append("- Pets - Removed legacy StatLossAfterTame behavior<br>");
			builder.Append("- Quest - Sage Artifact quest has been ported to ML Quest System<br>");
			builder.Append("- Quest - Sage Artifact quest now involves townsfolk<br>");
			builder.Append("- Quest - Updated most quests to be limited to discovered facets<br>");
			builder.Append("- Settings - Added a setting to require eating Powerscrolls in order<br>");
			builder.Append("- Settings - Lower Mana Cost (LMC) is now capped at 40%<br>");
			builder.Append("- Settings - Lower Reagent Cost (LRC) is now capped at 100%<br>");
			builder.Append("- Settings - Implement max Paralyze duration setting<br>");
			builder.Append("- Skill - Skills gains are accelerated to 70 but reduced at 85/95/105/110/115<br>");
			builder.Append("- Skill - Healing is now an activatable skill that can remove poison/bleed or heal you<br>");
			builder.Append("- Skill - Healing now gathers a portion over time and has a big hit at the end<br>");
			builder.Append("- Skill - Hiding cooldown is increased to 4 seconds, up from 1s and 2s<br>");
			builder.Append("- Skill - Spiritualism now restores Mana when a corpse is consumed<br>");
			builder.Append("- Skill - Masters in Remove Trap have a chance to avoid death from killer tiles<br>");
			builder.Append("- Skill - Searching can detect killer tiles<br>");
			builder.Append("- Skill - Magic Resistance skill now provides more resistance at lower skill<br>");
			builder.Append("- Skill - Arms Lore no longer provides an OnHit damage bonus<br>");
			builder.Append("- Skill - Arms Lore now helps prevent durability damage<br>");
			builder.Append("- Skill - Taming can now gain every time a pet levels up<br>");
			builder.Append("- Skill - Creatures with >= 10k Fame will anger on tame by default<br>");
			builder.Append("- Skill - Herding now increases pet experience gained<br>");
			builder.Append("- Skill - Herding can now be gained by issuing commands<br>");
			builder.Append("- Skill - Herding can prevent Loyalty loss when pets are disobedient<br>");
			builder.Append("- Spell - Players must be friend or higher to use any spell in a house<br>");
			builder.Append("- Spell - Paladin spells require 1 stamina per 1 mana cost<br>");
			builder.Append("- Spell - Creatures now vocalize Mantras when they cast spells<br>");
			builder.Append("- Spell - Rewrite Spell Bar configuration gump<br>");
			builder.Append("- Spell - Noble Sacrifice now works on pets<br>");
			builder.Append("- Stats - Mana Regen cap reduced to 18, down from 36<br>");
			builder.Append("- Stats - Holy Man now executes skill checks when casting spells<br>");

			builder.Append("<br>");
			builder.Append("Fixes<br>");
			builder.Append("- Combat - Ranged attacks are now prevented while being pacified<br>");
			builder.Append("- Combat - Peacemake debuff is only removed at the appropriate time<br>");
			builder.Append("- Combat - Mobs now bypass reagent check<br>");
			builder.Append("- Commands - Update [CorpseClear to actually remove all bodies<br>");
			builder.Append("- Commands - Update [Password to no longer log plain text passwords<br>");
			builder.Append("- Craft - Candelabras now cap at 95 skill rather than 195<br>");
			builder.Append("- Craft - Tinker recipes use Boards instead of Logs<br>");
			builder.Append("- Craft - Fixed an issue where enhancing was succeeding instead of failing<br>");
			builder.Append("- Gather - More tiles are now mineable<br>");
			builder.Append("- Gather - Added system message when digging up Dwarven ore/granite<br>");
			builder.Append("- Gather - The 'Resources' server setting is now limited by the amount of resources in the harvest bank<br>");
			builder.Append("- Gather - Drop harvested items to ground when backpack is full<br>");
			builder.Append("- Gather - Fix InvalidCastException when Fishing<br>");
			builder.Append("- Gather - Fix issue where saplings were choppable<br>");
			builder.Append("- Gather - Fix elementals spawning with gargoyle pickaxes<br>");
			builder.Append("- Gather - Graverobbing no longer creates orphaned chests<br>");
			builder.Append("- Gather - Graverobbing no longer creates orphaned zombies<br>");
			builder.Append("- Gump - Alien Players who use Tithe to pay for a res from another player are no longer double penalized<br>");
			builder.Append("- Gump - Sending buttons that don't exist will now disconnect the Player<br>");
			builder.Append("- Gump - Remove redundant quiver damage qualifier<br>");
			builder.Append("- Gump - Summon Familiar gump is now fixed<br>");
			builder.Append("- Gump - Jedi/Syth spells can be cast from main spellbook page again<br>");
			builder.Append("- Gump - Fugitives can now join the Assassin guild<br>");
			builder.Append("- Gump - Fugitives can now join the Black Magic guild<br>");
			builder.Append("- Item - Added missing Powerscrolls (Begging, Camping, Forensics, Mercantile, Tasting)<br>");
			builder.Append("- Item - Lucky horse shoe now work on Instruments and Quivers<br>");
			builder.Append("- Item - Unidentified items with deleted contents are now properly deleted<br>");
			builder.Append("- Item - Fix InvalidCastException when monsters rummage an ElementalSpellbook<br>");
			builder.Append("- Item - Fix monsters stamping their name on an un-owned MysticSpellbook<br>");
			builder.Append("- Item - Fix issue with Relic Tablets where they would rotate instead of open when in a Player's backpack in a house<br>");
			builder.Append("- Item - Horse Armor only gives bonus once<br>");
			builder.Append("- Item - Horse Armor can no longer be infinitely farmed<br>");
			builder.Append("- Item - Repair and Durability potions now work on clothing<br>");
			builder.Append("- Item - Stone face trap is now choppable<br>");
			builder.Append("- Item - Item generation now has greater variation in resource selection<br>");
			builder.Append("- Item - Young player maps are now decodable<br>");
			builder.Append("- Item - You can now steal with any type of pugilist gloves<br>");
			builder.Append("- Item - Ten foot pole now conveys initial % avoidance<br>");
			builder.Append("- Item - Add missing bone from polishing brush<br>");
			builder.Append("- Misc - Set Map when [scan players<br>");
			builder.Append("- Misc - Fix typo in RangeCheck()<br>");
			builder.Append("- Misc - Buffs/Debuffs now end on the Server before the Client timer elapses<br>");
			builder.Append("- Misc - Stop deleting an item when it's stacked with itself<br>");
			builder.Append("- Misc - Monster races now get the configured starting gold<br>");
			builder.Append("- Misc - Elementalist weapon damage bonus is now applied<br>");
			builder.Append("- Misc - Removed `Bridge of Tul'mok` region<br>");
			builder.Append("- Misc - Hidden chests are now deleted after they are revealed<br>");
			builder.Append("- Misc - Fix null ref in BaseCreature.OnAfterSpawn()<br>");
			builder.Append("- Misc - Mongbat tower at Devil Guard is now properly capped<br>");
			builder.Append("- Misc - Dispose of orphaned Data.ref stream writer<br>");
			builder.Append("- Misc - Potion breaking trap now deletes unidentified potion containers<br>");
			builder.Append("- Misc - Monster race paperdoll graphics are restored after restart<br>");
			builder.Append("- Misc - Fix potential null ref during icon removal<br>");
			builder.Append("- Misc - Coffers now require you to be within 3 tiles to snoop it<br>");
			builder.Append("- Misc - Lands are now immediately discovered when you load into them<br>");
			builder.Append("- Misc - Elemental Steed are no longer turned into a horse after [buildworld<br>");
			builder.Append("- Misc - Trapped chests could be autolooted before successfully opening them<br>");
			builder.Append("- Mobs - Winter Wolf now has Skills set<br>");
			builder.Append("- Pets - Loyalty now refreshes when it changes<br>");
			builder.Append("- Quest - Fix bug where the quest default of 'the Dungeon of Doom' could never be satisfied<br>");
			builder.Append("- Spell - BloodOath could linger up to 1s too long on the Server<br>");
			builder.Append("- Spell - Bard songs weren't blocked when no instrument was assigned<br>");
			builder.Append("- Spell - Bard songs weren't blocked when below required skill level<br>");
			builder.Append("- Spell - Mirror image now has the correct buff name<br>");
			builder.Append("- Spell - Dispel/Banish now properly indicate when a target cannot be dispelled<br>");
			builder.Append("- Spell - Death Knight spells no longer have a redundant failure check<br>");
			builder.Append("- Spell - Syth spells no longer have a redundant failure check<br>");
			builder.Append("- Spell - Jedi spells no longer have a redundant failure check<br>");
			builder.Append("- Spell - Fast-move spells now clean up removal timers<br>");
			builder.Append("- Spell - Fast-move spells and items now work consistently<br>");
			builder.Append("- Spell - Resurrect spells now work on pets<br>");
			builder.Append(SEPARATOR_LINE);

			///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

			builder.Append("Re-baseline - September 28 2024<br>");
			builder.Append("- Reset repository to Adventurers of Akalabeth version 'Samurai - 25 September 2024'<br>");
			builder.Append(SEPARATOR_LINE);

			///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

			builder.Append("Inception - 4 August 2024<br>");
			builder.Append("- Ultima: Memento begins using Adventurers of Akalabeth version 'Necromancer - 26 July 2024'<br>");
			builder.Append("<br>");

			return builder.ToString();
		}
	}
}